# permissions for end users to edit daloradius.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daloradius-editor-role
rules:
- apiGroups:
  - app.k8s-cluster.net.xuegaogg.com
  resources:
  - daloradius
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s-cluster.net.xuegaogg.com
  resources:
  - daloradius/status
  verbs:
  - get
